name: Deploy Web
on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "packages/nodes-base/**"
      - "packages/db/**"
      - "packages/eslint-config/**"
      - "packages/typescript-config/**"
      - ".github/workflows/deploy-web-to-vm.yml"
      - "docker/Dockerfile.web"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image with Combined Secret
        run: |
          # Save the secret to a temporary file
          echo "${{ secrets.BUILD_ENV_FILE }}" > .env.build

          # Build Docker image with secret
          docker build \
            --secret id=envfile,src=.env.build \
            -t ikrambagban/n8n-web:${{ github.sha }} \
            -f docker/Dockerfile.web \
            .
          docker push ikrambagban/n8n-web:${{ github.sha }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ikrambagban/n8n-web:${{ github.sha }}
            docker network inspect n8n-network || docker network create n8n-network
            docker stop n8n-web || true
            docker rm n8n-web || true
            docker run -d \
              --name n8n-web \
              --restart always \
              --network n8n-network \
              -p 4000:4000 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e NODE_ENV="production" \
              -e PORT="4000" \
              ikrambagban/n8n-web:${{ github.sha }}
